qubits = 24

[[gates]]
name = "H"
targets = [2]

[[gates]]
name = "X"
targets = [3]

[[gates]]
name = "Y"
targets = [1]

[[gates]]
name = "CNOT"
targets = [0, 1]

[[gates]]
name = "GHZ"
targets = [] 
